### ISSUE TITLE
集成到项目中运行报错

### ISSUE THREAD

**Issue by FOnlyJack** [polyv/polyv-android-cloudClass-sdk-demo#3]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zn.hxwm.hxwm_android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zn.hxwm.hxwm_android-1/lib/arm, /data/app/com.zn.hxwm.hxwm_android-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]] couldn't find "libagora-rtc-sdk-jni.so"
        at io.a.k.a.a(RxJavaPlugins.java:366)
        at io.a.a.b.b$b.run(HandlerScheduler.java:111)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6802)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zn.hxwm.hxwm_android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zn.hxwm.hxwm_android-1/lib/arm, /data/app/com.zn.hxwm.hxwm_android-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]] couldn't find "libagora-rtc-sdk-jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1530)
        at io.agora.rtc.internal.RtcEngineImpl.initializeNativeLibs(RtcEngineImpl.java:273)
        at io.agora.rtc.RtcEngine.create(RtcEngine.java:48)

**Comment by FOnlyJack** [comment]
引用了这个  api 'com.easefun.polyv:polyvSDKCloudClass:0.5.0'  为什么报上面的错呢?

**Comment by FOnlyJack** [comment]
@jlayi

**Comment by jlayi** [comment]
![image](https://user-images.githubusercontent.com/25811375/52828265-10524200-3103-11e9-9318-46deb9f71458.png)
可以加上这个配置看下。

**Comment by FOnlyJack** [comment]
@jlayi   ok 了
