### ISSUE TITLE
polyvSDKCloudClass:0.14.0.05报错

### ISSUE THREAD

**Issue by lt19931203** [polyv/polyv-android-cloudClass-sdk-demo#7]
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long com.plv.foundationsdk.ijk.player.media.PLVPlayerNative.getCurFrameAgoraUserTC(java.lang.Object) (tried Java_com_plv_foundationsdk_ijk_player_media_PLVPlayerNative_getCurFrameAgoraUserTC and Java_com_plv_foundationsdk_ijk_player_media_PLVPlayerNative_getCurFrameAgoraUserTC__Ljava_lang_Object_2)
        at com.plv.foundationsdk.ijk.player.media.PLVPlayerNative.getCurFrameAgoraUserTC(Native Method)
        at com.easefun.polyv.cloudclass.video.PolyvCloudClassVideoView$1.accept(PolyvCloudClassVideoView.java:147)
        at com.easefun.polyv.cloudclass.video.PolyvCloudClassVideoView$1.accept(PolyvCloudClassVideoView.java:141)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:900) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8349) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by Yukino0812** [comment]
建议检查abiFilters的配置，云课堂仅支持[arm64-v8a、armeabi-v7a、x86]三种架构。同时检查是否存在项目本地配置了旧版so库，或者多播放器同时集成导致so冲突的情况。
